### ISSUE TITLE
grch38 support

### ISSUE THREAD

**Issue by timchu90** [shahcompbio/single_cell_pipeline#126]
Hi, 

Thanks again for your work on this project. 
Are there any plans to support grch38 reference for this project, or perhaps documentation on how to generate required refdata for other references?

Thanks!
Tim Chu
NYGC

**Comment by amcpherson** [comment]
Thanks for reaching out Tim,
Yes, grch38 support is in the backlog, hopefully to be worked on in the medium term (next few months).  This can possibly be accelerated if you have an immediate need.  We plan to document the process of generating the reference data starting with align, hmmcopy and annotation.  The reference data for the remaining parts of the pipeline may be developed as needed, though they may come after a rewrite we are undertaking.

Cheers,
Andrew
