### ISSUE TITLE
Training data for cell quality classifier

### ISSUE THREAD

**Issue by yifnzhao** [shahcompbio/single_cell_pipeline#194]
Hi, I would like to try the cell quality classifier to assess the quality of my own dataset. I am wondering if the initial training data (as described in Laks et al 2019), or the trained model, is available. Thanks in advance!

**Comment by diljotgrewal** [comment]
hi, 
Yes the training data is available in the reference dataset directory in classifier_training_data.h5 file. 

Code for loading and training the classifier is 
https://github.com/shahcompbio/single_cell_pipeline/blob/master/single_cell/workflows/qc_annotation/scripts/classify.py#L73
