### ISSUE TITLE
General question about HG19 vs GRCH37

### ISSUE THREAD

**Issue by zhaoxiaofei** [shahcompbio/single_cell_pipeline#206]
Hello there, 

I would like to run hmmcopy with some single-cell WGS data. 
1 - Is it OK to run according to the instruction listed here: https://github.com/compbiofan/SingleCellCNABenchmark ? The result does not look OK to me so far: lots of ploidies are wronly estimated.  
2 - If I have BAM files aligned to HG19 with chr (i.e., chromosome name is chr22 not 22), is there any way I can feed such BAM files directly to hmmcopy? I don't want to transform back to fastq and then realign to the reference genome without chr. 

Best,

**Comment by diljotgrewal** [comment]
Hi,

We've stopped development on this project and have moved on to mondrian:
https://github.com/mondrian-scwgs/mondrian

If you'd like to run hmmcopy: then please use the following docker container:
 https://quay.io/repository/mondrianscwgs/hmmcopy
 
 You can run hmmcopy with the following command:

`       hmmcopy_utils readcounter --infile ~{bamfile} --outdir output/ -w 500000 --chromosomes ~{sep=" "chromosomes} \
        -m 20 --exclude_list ~{repeats_satellite_regions} --tempdir all_cells_temp --ncores ~{num_threads}`


`        hmmcopy_utils hmmcopy \
      --readcount_wig ~{readcount_wig} \
        --gc_wig_file ~{gc_wig} \
        --map_wig_file ~{map_wig} \
        --metrics metrics.csv.gz \
        --params params.csv.gz \
        --reads reads.csv.gz \
        --segments segments.csv.gz \
        --output_tarball hmmcopy_data.tar.gz \
        --reference ~{reference} \
        --segments_output segments.pdf \
        --bias_output bias.pdf \
        --cell_id ~{cellid} \
        --tempdir output \
        --map_cutoff ~{map_cutoff}`

Full reference datasets are available for download, please see documentation here
https://mondrian-scwgs.github.io/mondrian/#/quickstart/README

GRCh38/hg19 reference is also available there, and it contains chr prefix. Chr prefixes are supported by hmmcopy.

**Comment by zhaoxiaofei** [comment]
Thank you for your quick answer: I got the following problem when trying to download GRCh37/hg19. 
```
 wget https://mondriantestdata.s3.amazonaws.com/mondrian-ref-GRCh37.tar.gz
--2023-04-16 23:58:54--  https://mondriantestdata.s3.amazonaws.com/mondrian-ref-GRCh37.tar.gz
Resolving mondriantestdata.s3.amazonaws.com (mondriantestdata.s3.amazonaws.com)... 52.217.88.132, 3.5.25.152, 52.216.241.124, ...
Connecting to mondriantestdata.s3.amazonaws.com (mondriantestdata.s3.amazonaws.com)|52.217.88.132|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-04-16 23:58:55 ERROR 403: Forbidden.

```
But it looks like "wget https://mondriantestdata.s3.amazonaws.com/mondrian-ref-20-22.tar.gz"
 work fine. 
Do you know what might be the problem for downloading GRCh37?

**Comment by diljotgrewal** [comment]
apologies for the delay, link fixed. 
Closing issue, please open issues under mondrian project. Thanks!!
