### ISSUE TITLE
extract_quality_metrics.py

### ISSUE THREAD

**Issue by seanbeatty** [shahcompbio/single_cell_pipeline#7]
[stand_mad in the statsmodels package is deprecated as of statsmodels 0.70](http://www.statsmodels.org/0.6.1/_modules/statsmodels/robust/scale.html#stand_mad) (current version is 0.10.1). As of 0.6.1 statsmodels stand_mad has called mad. 

It looks like replacing L13 of [extract_quality_metrics.py](https://github.com/shahcompbio/single_cell_pipeline/blob/master/single_cell/workflows/hmmcopy/scripts/extract_quality_metrics.py) will fix it. 

from statsmodels.robust.scale import stand_mad) 

with

from statsmodels.robust.scale import mad as stand_mad

will fix the issue. 

Thanks for making your code open source!

**Comment by diljotgrewal** [comment]
That script isn't used by the pipeline anymore. Those metrics are now computed by the R script, the python script is deprecated. If you're using that script for your work, could you please start a PR and I'll merge it in.
